#!/usr/bin/env bash

# Create a release.
# Usage: ./release.sh <tag>

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <tag>"
    exit 1
fi

tag="$1"

# Check for untracked files
untracked_files=$(git ls-files . --exclude-standard --others)
if [[ -n "$untracked_files" ]]; then
    echo "Error: Please stash or remove the untracked files!"
    exit 1
fi

# Update the changelog
echo "Updating the changelog"
git-cliff --config .cliff.toml --tag "$tag" --output CHANGELOG.md

# Format the newly created changelog file
just fmt

# Write the new_version to a file 'version'
echo "$tag" > version

# Commit a release
git add --all
git commit --message "$tag"
git show
git tag --sign --annotate "$tag" --message "For details, see the CHANGELOG.md"
git tag --verify "$tag"
