#!/usr/bin/env -S just --justfile

shebang := if os() == 'windows' { 'powershell.exe' } else { '/usr/bin/sh' }

set dotenv-load := true

alias d := dev
alias r := run
alias f := fmt
alias l := lint
alias p := publish

# List available commands.
_default:
    just --list --unsorted

# Setup the repository
setup:
    cargo watch --version || cargo install cargo-watch

# Develop the app.
dev:
    cargo watch -x 'clippy --locked --all-targets --all-features'

# Develop the app.
run:
    cargo run

# Format the codebase.
fmt:
    cargo fmt --all

# Check is the codebase properly formatted.
fmt-check:
    cargo fmt --all -- --check

# Lint the codebase.
lint:
    cargo clippy --locked --all-targets --all-features

# Check the documentation.
_doc-check:
    cargo doc --all-features --no-deps

# Link the binaries
publish:
    cargo test

# Tasks to make the code-base comply with the rules. Mostly used in git hooks.
comply: fmt lint _doc-check

# Check if the repository comply with the rules and ready to be pushed.
check: fmt-check lint _doc-check

# Check dependencies health. Pass `--write` to uppgrade dependencies.
up arg="":
    #!{{ shebang }}
    if [ "{{ arg }}" = "--write" ]; then
        cargo upgrade
        cargo update
    else
        cargo outdated --root-deps-only
    fi;
