#! /bin/sh

#
# WM independent hotkeys
#

# Program launcher
super + h; n
  rofi -modi run,drun,window -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font "Fira Code 14"

super + h; e
  rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'

# Take a screenshot
super + shift + p
  flameshot gui

#
# bspwm hotkeys
#

# Quit/restart bspwm
super + alt + {q,r}
  bspc {quit,wm --restart}

# Close and kill
super + {_,shift + }q
  bspc node --{close, kill}

# Alternate between the tiled and monocle layout
super + h; m
  bspc desktop --layout next

#
# State
#

# window state
super + h; {t, shift + t, s, f}
  bspc node --state {tiled, pseudo_tiled, floating, fullscreen}


#
# Flags
#

# Set the node flags
super + h; {l,u,y,i}
  bspc node --flag {marked,locked,sticky,private}

#
# Focus
#

# Focus to next window

# I don't bspwm to focus to Workrave's applet
# It is floating in every desktop and I don't want to
# trip over it while switching windows
# Using `manage=off` disables everything. So I can't easily move it around.

# `local` instruct bspwm to operate only in current desktop
# `window` instruct bspwm to skip the empty node
super + {_, shift+}Return
  bspc node --focus {next.local.!sticky.window, prev.local.!sticky.window}

# Focus to next workspace
super + {_, shift+}Tab
  bspc desktop --focus {next.occupied.local, prev.occupied.local}

# Focus or send to the given desktop
super + {_,shift + }{4,5,6,7}
  bspc {desktop --focus,node --to-desktop} '{1,2,3,4}'

# Jump to another workspace
super + {4,5,6,7}
  bspc desktop --focus {1,2,3,4}

#
# Preselect
#

# Spit horizontal & split vertical, like in i3
super + h; {h,v}
  bspc node --presel-dir {east,south}

# Cancel
super + h; Escape
  bspc node --presel-dir cancel

#
# Resize
#

# Expand a window by moving one of its side outward.
# Looks odd?. I am using colemak.
super + alt + {n,e,u,i}
  bspc node --resize {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# Contract a window by moving one of its side inward
super + alt + shift + {n,e,u,i}
  bspc node --resize {right -20 0,top 0 20,bottom 0 -20,left 20 0}


#
# Move
#

# Send the newest marked node to the newest preselected node
super + h; a
  # bspc node newest.marked.local -n newest.!automatic.local
  bspc node --to-node newest.\!automatic.local

# Swap the current node and the biggest window
super + h; g
  bspc node --swap biggest.window

#
# Documentation
#

# To move window to pre-select area:
# 1. Pre-select the area using `s-h; v` or `s-h; h`
# 2. Move the focus to the target window
# 3. Tell bspwm to move current window to pre-selected area using `s-h; a`

