#! /bin/sh

#
# wm independent hotkeys
#

## program launcher
super + n; n
    rofi -modi run,drun,window -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font "Fira Code 14"

super + n; e
    rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'

## take a screenshot
super + shift + p
    flameshot gui

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

## focus or send to the given desktop
super + {_,shift + }{4,5,6,7,8}
	bspc {desktop -f,node -d} '{1,2,3,4,5}'

## jump to another workspace
super + {4,5,6,7,8}
	bspc desktop --focus {1,2,3,4,5}

# Using chain in bspwm is hard.
# it has no visible mode feedback such i3
# ## set window style
# super + w; {t, p, f}
    #   bspc node -t {tiled, pseudo_tiled, floating}

#window state
super + e; {t, shift + t, s, f}
    bspc node -t {tiled, pseudo_tiled, floating, fullscreen}

## spit horizontal & split vertical, like in i3
super + e; {h,v}
    bspc node -p {east,south}

# focus
# next window, next workspace
super + {Return, Tab}
    bspc {node -f next.local, desktop -f next.occupied.local}
