#! /bin/sh

## workspace name
# bspc monitor -d 1 2 3 4
bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor -d "" "" "" ""

## common bspwm configuration
bspc config border_width        2
bspc config window_gap         	5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config top_padding 24

## color settings
bspc config normal_border_color "#d8dee9"
bspc config focused_border_color "#3b4252" 

#
# window rules
#

## workspace 4 (labs)
# bspc rule -a Wezterm desktop='^1' follow=on focus=on
bspc rule -a Wezterm desktop='^4'
bspc rule -a Emacs desktop='^4'

## workspace 5 (web browsers)
# bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a Firefox desktop='^5'

## workspace 6
#bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a Thunar desktop='^6'

## workspace 7 
# bspc rule -a Pavucontrol desktop='^4' state=floating follow=on
# bspc rule -a Arandr desktop='^4' state=floating follow=on
# bspc rule -a mpv desktop='^4' follow=on focus=on

## need to be floating
bspc rule -a feh state=floating follow=on

#
# autostart
#

# bitmap fonts
xset fp+ ~/.local/share/fonts &

## window compositor
pkill picom
picom &

# status bar
pkill polybar
$HOME/.config/polybar/launch.sh &

# keybind daemon
pkill sxhkd
sxhkd &

## set the wallpaper
# feh --bg-fill $HOME/wallpapers/wallpaper.jpg &
pkill feh
feh --recursive --bg-fill --randomize ~/wallpapers &

## load dunst
pkill dunst
dunst &

# network applet
nm-applet &

# clipboard manager
pkill greenclip
greenclip daemon &

## reload the cursor theme
xsetroot -cursor_name left_ptr &

light -S 10 &

pkill auto-suspend
auto-suspend &

pkill workrave
workrave &

# pkill aw-qt
# aw-qt &

