#! /bin/sh

# local binaries

# Monitor naming and switching now fully managed by bspwm
# Using these there configuration. It solved the unordered,
# duplicate, and overrides window number.
# Handling them manually is painful.
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

## common bspwm configuration
bspc config border_width          2
bspc config window_gap            5
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
# If set to `true`, I can't use keybindings to
# change focus
bspc config focus_follows_pointer false
bspc config top_padding           24

## color settings
bspc config focused_border_color "#4c566a"
bspc config normal_border_color "#d8dee9"

#
# window rules
#

##  labs
# bspc rule -a Wezterm desktop='^1' follow=on focus=on
bspc rule -a Wezterm desktop='^1' focus=on
bspc rule -a Emacs desktop='^1' focus=on state=tiled

## web browsers
bspc rule -a Firefox desktop='^2' focus=on
bspc rule -a 'firefox:*:Mozilla Firefox'  desktop='^2' focus=on

## file managers
bspc rule -a Thunar desktop='^3' focus=on

## multimedia
bspc rule -a Pavucontrol desktop='^4' state=floating
# Don't specify Arandr workspace. I need to invoke it from anywehere
bspc rule -a Arandr state=floating
bspc rule -a "Screen Layout Editor" desktop='^4' state=floating
bspc rule -a mpv desktop='^4' focus=on

## need to be floating
bspc rule -a feh state=floating follow=on

#
# autostart
#

## brightness
pkill auto-brightness
auto-brightness &

## window compositor
pkill picom
picom &

# status bar
pkill polybar
"$HOME"/.config/polybar/launch.sh &

# keybind daemon
pkill sxhkd
sxhkd &

## set the wallpaper
pkill feh
feh --recursive --bg-fill --randomize ~/wallpapers &

## load dunst
pkill dunst
dunst &

# network applet
nm-applet &

# clipboard manager
pkill greenclip
greenclip daemon &

# reload the cursor theme
# otherwise the cursor will looks odd
xsetroot -cursor_name left_ptr &

pkill auto-suspend
auto-suspend &

pkill workrave
workrave &

# pkill aw-qt
# aw-qt &
