#! /bin/sh

# local binaries

# Monitor naming and switching now fully managed by bspwm
# Using these there configuration. It solved the unordered,
# duplicate, and overrides window number.
# Handling them manually is painful.
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

## common bspwm configuration
bspc config border_width          2
bspc config window_gap            5
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
# If set to `true`, I can't use keybindings to
# change focus
bspc config focus_follows_pointer false
bspc config top_padding           24

## color settings
bspc config focused_border_color "#4c566a"
bspc config normal_border_color "#d8dee9"

#
# window rules
#

# Use cases:
# - `follow=on` if you click a link from other workspace, the workspace will be switched
# to the workspace where the web browser is running or opened.

bspc rule --add Wezterm desktop='^1'
# Emacs is floating by default
bspc rule --add Emacs desktop='^1' state=tiled

# `follow=on` I want the desktop to switch to the browser
# after I open the link from other app in different desktop
bspc rule --add Firefox follow=on

# Don't specify Arandr workspace. I need to invoke it from anywehere
bspc rule --add Arandr

bspc rule --add "Screen Layout Editor" desktop='^4'
bspc rule --add mpv desktop='^4'
bspc rule --add Workrave state=sticky


#
# autostart
#

## brightness
# pkill auto-brightness
# auto-brightness &

## window compositor
pkill picom
picom &

# status bar
pkill polybar
"$HOME"/.config/polybar/launch.sh &

# keybind daemon
pkill sxhkd
sxhkd &

## set the wallpaper
pkill feh
feh --recursive --bg-fill --randomize ~/wallpapers &

## load dunst
pkill dunst
dunst &

# network applet
nm-applet &

# clipboard manager
pkill greenclip
greenclip daemon &

# reload the cursor theme
# otherwise the cursor will looks odd
xsetroot -cursor_name left_ptr &

# Nowadays, I charge my laptop all the time
# and stop the charge using tlp

# pkill auto-suspend
# auto-suspend &

pkill workrave
workrave &

# pkill aw-qt
# aw-qt &
