#!/usr/bin/env bash

# Script Name: ack-remove-whitespace
# Description: Remove trailing whitespace across multiple files
# Credits: https://stackoverflow.com/a/16246948/6000005
#
# Usage: ./ack-remove-whitespace
#
# Dependencies: ack

ack --print0 -l '[ \t]+$' | xargs -0 -n1 perl -pi -e 's/[ \t]+$//'
