#!/usr/bin/env fish

#
# Mount external harddrive
#

# I prefer maintaining the mounting path for my HDD as designated by 'GNOME Disks' or 'Nautilus'.
# To make it simpler, instead of doing wizard thing on `fstab`, I just do it here

# sudo fdisk -l
udisksctl mount -b /dev/sdb1
udisksctl mount -b /dev/sdb2

#
# SSH
#

# ssh-add -l
ssh-add ~/.ssh/github
