#!/bin/fish

# set selection (cliphist list | fuzzel --dmenu | cliphist decode)
# set selection (cliphist list | wofi --show dmenu | cliphist decode)
set selection (cliphist list | anyrun --plugins libstdin.so | cliphist decode)

if test "$selection" != ""
    # Using `echo` will strip the new lines
    printf "%s" "$selection" | wl-copy
end
