#!/bin/bash

FILES=(
  "clean"
  "names"
  "sfetch"
)

fmt() {
  for file in "${FILES[@]}"; do
    rustfmt bin/opt/bin/public/"$file"
  done
}


case $1 in
"fmt") fmt ;;
*) echo "unsupported action" ;;
esac
