#!/bin/bash

FILES=(
  "clean"
  "ding"
  "update")

fmt() {
  for file in "${FILES[@]}"; do
    shfmt --list --write --indent 2 bin/opt/bin/public/"$file"
  done
}

lint() {
  for file in "${FILES[@]}"; do
    shellcheck bin/opt/bin/public/"$file"
  done
}

case $1 in
"fmt") fmt ;;
"lint") lint ;;
*) echo "unsupported action" ;;
esac
