#!/bin/bash

FILES=(
  "clean"
  "ding"
  "post-install"
  "up"
  "update"
  "wezterm-here")

fmt() {
  for file in "${FILES[@]}"; do
    shfmt --list --write --indent 2 bin/bin/public/"$file"
  done
}

lint() {
  for file in "${FILES[@]}"; do
    shellcheck bin/bin/public/"$file"
  done
}

case $1 in
"fmt") fmt ;;
"lint") lint ;;
*) echo "unsupported action" ;;
esac
